version: '3.8'

services:
  # O Motor (API de Streaming)
  backend:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  # O Rosto (Interface Streamlit)
  frontend:
    build: .
    command: streamlit run src.interface/app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - backend